---
openapi: 3.0.1
info:
  title: CXFirst API V1
  version: v1
paths:
  "/hierarchies":
    get:
      summary: Retrieves the list of configured hierarchies
      tags:
      - Hierarchies
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Hierarchies
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                    - hierarchy_branches:
                      - _link:
                          self: "/api/v1/hierarchies/arbre-1/branches/id_region"
                        slug: id_region
                        title: id_region
                      - _link:
                          self: "/api/v1/hierarchies/arbre-1/branches/id_agence"
                        slug: id_agence
                        title: id_agence
                      root_hierarchy_title: Enseigne
                      slug: arbre-1
  "/hierarchies/{slug}":
    get:
      summary: Retrieves a hierarchy by slug
      tags:
      - Hierarchies
      security:
      - bearerAuth: []
      parameters:
      - name: slug
        in: path
        required: true
        description: Slug of the hierarchy
        schema:
          type: string
      responses:
        '200':
          description: Hierarchy
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                      hierarchy_branches:
                      - _link:
                          self: "/api/v1/hierarchies/arbre-1/branches/id_region"
                        slug: id_region
                        title: id_region
                      - _link:
                          self: "/api/v1/hierarchies/arbre-1/branches/id_agence"
                        slug: id_agence
                        title: id_agence
                      root_hierarchy_title: Enseigne
                      slug: arbre-1
        '404':
          description: Not found
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    message: Not found
  "/hierarchies/{hierarchy_slug}/branches/{branch_slug}":
    get:
      summary: Retrieve a hierarchy branch by slug
      tags:
      - Hierarchies
      security:
      - bearerAuth: []
      parameters:
      - name: hierarchy_slug
        in: path
        required: true
        description: Slug of the hierarchy
        schema:
          type: string
      - name: branch_slug
        in: path
        required: true
        description: Slug of the branch to retrieve
        schema:
          type: string
      responses:
        '200':
          description: Hierarchy Branch
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                      _link:
                        self: "/api/v1/hierarchies/arbre-1/branches/id_agence"
                      slug: id_agence
                      title: id_agence
                      values:
                      - code: R_2_4
                        title: DEFENSE
                      - code: R_1_4
                        title: PARIS
        '404':
          description: Not found
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    message: Not found
  "/sites":
    get:
      summary: Retrieves the list of sites
      tags:
      - Sites
      security:
      - bearerAuth: []
      parameters:
      - name: code
        in: query
        description: Filter by code
        schema:
          type: string
      - name: page
        in: query
        description: Page
        schema:
          type: integer
      - name: per_page
        in: query
        description: 'Number of items per page (max : 100)'
        schema:
          type: integer
      responses:
        '200':
          description: Sites
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                    - code: LADEFENSE
                      title: AXA IMP
                    - code: ROUBAIX
                      title: AXA IMP
                    - code: MARSEILLE
                      title: AXA IMP
                    meta:
                      total: 3
                      total_pages: 1
                      current_page: 1
                      per_page: 5
                      next:
                      previous:
  "/sites/{code}":
    get:
      summary: Retrieves a list of sites
      tags:
      - Sites
      security:
      - bearerAuth: []
      parameters:
      - name: code
        in: path
        description: Site code
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Site
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                      active: true
                      checksum: 0f9f22974144f07473bfc1509a0fb4f5aba83a89ed925c72a2b506b7fa14cdfd
                      code: MARSEILLE
                      id: 685cf57d9af7038bcbd559a3
                      network_manager_id: ''
                      properties:
                        code: MARSEILLE
                        id: 685cf57d9af7038bcbd559a3
                        active: true
                        title: AXA IMP
                        id_region:
                        - R_2
                        id_agence:
                        - R_2_4
                      title: AXA IMP
        '404':
          description: Not found
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    message: Not found
  "/streams/{stream_slug}/pages":
    get:
      summary: List pages
      tags:
      - Pages
      security:
      - bearerAuth: []
      parameters:
      - name: stream_slug
        in: path
        description: Slug of stream
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                    - _links:
                        self: "/api/v1/streams/sondage/pages/scores"
                      slug: scores
                      title: Scores
                      type: scores_page
        '404':
          description: Not found
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    message: Not found
  "/streams/{stream_slug}/pages/{slug}":
    get:
      summary: show page
      tags:
      - Pages
      security:
      - bearerAuth: []
      parameters:
      - name: stream_slug
        in: path
        description: Slug of stream
        required: true
        schema:
          type: string
      - name: slug
        in: path
        description: Slug of page
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                      _links:
                        self: "/api/v1/streams/sondage/pages/scores"
                      slug: scores
                      title: Scores
                      type: scores_page
        '404':
          description: Not found
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    message: Not found
  "/streams/{stream_slug}/data":
    get:
      summary: Get a list of raw data
      tags:
      - Data
      security:
      - bearerAuth: []
      parameters:
      - name: stream_slug
        in: path
        description: Stream slug
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: Page
        schema:
          type: integer
      - name: per_page
        in: query
        description: Per page
        schema:
          type: integer
      - name: from
        in: query
        description: yyyy-mm-dd
        schema:
          type: string
      - name: to
        in: query
        description: yyyy-mm-dd
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                    - _links:
                        self: "/api/v1/streams/sondage/data/685cf57f9af7038bcbd55a8c"
                        public_url: "/q/3aejccmkx2o2ozlq"
                        show: "/streams/sondage/answers/685cf57f9af7038bcbd55a8c/questionnaire"
                      created_at: '2025-06-26T09:23:43.445+02:00'
                      date: '2025-06-26'
                      has_alert: false
                      id: 685cf57f9af7038bcbd55a8c
                      site:
                        code: LADEFENSE
                      state: Non trait√©e
                      unique_identifier: unique_id_1_1
                      user:
                      values:
                        CITY: LADEFENSE
                        entry_header: '1'
                        DATE_PERIOD: '2018-01-01'
                        PLAY_UNO: '1'
                        PLAY_MONOPOLY: '1'
                    - _links:
                        self: "/api/v1/streams/sondage/data/685cf57f9af7038bcbd55a97"
                        public_url: "/q/d2gowgzg04y7roi9"
                        show: "/streams/sondage/answers/685cf57f9af7038bcbd55a97/questionnaire"
                      created_at: '2025-06-26T09:23:43.590+02:00'
                      date: '2025-06-26'
                      has_alert: true
                      id: 685cf57f9af7038bcbd55a97
                      site:
                        code: LADEFENSE
                      state: Non trait√©e
                      unique_identifier: unique_id_2_2
                      user:
                      values:
                        CITY: LADEFENSE
                        entry_header: '1'
                        DATE_PERIOD: '2018-01-01'
                        PLAY_UNO: '1'
                        PLAY_MONOPOLY: '1'
                    meta:
                      total: 0
                      total_pages: 0
                      current_page: 1
                      per_page: 50
                      next:
                      previous:
        '404':
          description: Not found
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    message: Not found
  "/streams":
    get:
      summary: Retrieves a list of streams
      tags:
      - Streams
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Streams
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                    - _links:
                        self: "/api/v1/streams/sondage"
                        pages: "/api/v1/streams/sondage/pages"
                        data: "/api/v1/streams/sondage/data"
                      slug: sondage
                      stream_type: single
                      title: Sondages
  "/streams/{slug}":
    get:
      summary: Retrieve the stream information
      tags:
      - Streams
      security:
      - bearerAuth: []
      parameters:
      - name: slug
        in: path
        required: true
        description: Slug of the stream
        schema:
          type: string
      responses:
        '200':
          description: Stream
          content:
            application/json:
              examples:
                example:
                  value:
                    data:
                      _links:
                        self: "/api/v1/streams/sondage"
                        pages: "/api/v1/streams/sondage/pages"
                        data: "/api/v1/streams/sondage/data"
                      pages:
                      - _links:
                          self: "/api/v1/streams/sondage/pages/scores"
                        slug: scores
                        title: Scores
                        type: scores_page
                      slug: sondage
                      stream_type: single
                      title: Sondages
        '404':
          description: Not found
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 404
                    message: Not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
servers:
- url: https://{subdomain}.mycxfirst.com/api/v1
  variables:
    subdomain:
      default: demo
